[project]
name = "module-1-question-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "notebook>=7.5.2",
    "pandas>=2.3.3",
    "pyarrow>=23.0.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
